#!/usr/bin/env bash
# install nginx in a new server
sudo apt update
sudo apt -y install nginx
sudo chmod 666 /var/www/html/index.nginx-debian.html
sudo chmod 666 /usr/share/nginx/html/index.html
echo "Holberton School for the win yeah!" > /var/www/html/index.nginx-debian.html
echo "Holberton School for the win yeah!" > /usr/share/nginx/html/index.html
sed -i  's/# pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000/rewrite \/redirect_me\/   https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-available/default
sudo service nginx restart