#!/usr/bin/env bash
# displays the numbers 1 to 20 and displays some messages

x=1
while [ "$x" -le 20 ]; do
    echo "$x"
    case "$x" in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    let x=x+1
done
